/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baiduren_lemontv_module_MirrorAccel */

#ifndef _Included_com_baiduren_lemontv_module_MirrorAccel
#define _Included_com_baiduren_lemontv_module_MirrorAccel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baiduren_lemontv_module_MirrorAccel
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_baiduren_lemontv_module_MirrorAccel_init
  (JNIEnv *, jclass);

/*
 * Class:     com_baiduren_lemontv_module_MirrorAccel
 * Method:    uninit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_baiduren_lemontv_module_MirrorAccel_uninit
  (JNIEnv *, jclass);

/*
 * Class:     com_baiduren_lemontv_module_MirrorAccel
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_baiduren_lemontv_module_MirrorAccel_create
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_baiduren_lemontv_module_MirrorAccel
 * Method:    destroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_baiduren_lemontv_module_MirrorAccel_destroy
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
